<?php
session_start();
include '../db.php';

// Set default timezone to Asia/Dhaka (fallback)
date_default_timezone_set('Asia/Dhaka');

// Ensure only admin can access this page
if ($_SESSION['role'] !== 'admin') {
    header('Location: ../login.php');
    exit;
}

// Retrieve user ID from session
$user_id = $_SESSION['user_id'];

// Get username from the database
$query = "SELECT username FROM users WHERE id = ?";
$stmt = $conn->prepare($query);

// Check if prepare is successful
if ($stmt === false) {
    die('MySQL prepare error: ' . $conn->error);
}

// Bind the parameter
$stmt->bind_param('i', $user_id);

// Execute the statement
$stmt->execute();

// Get the result
$result = $stmt->get_result();

if ($result) {
    $user = mysqli_fetch_assoc($result);
    $username = $user ? $user['username'] : ''; // Handle if no user is found
} else {
    echo "Error executing query: " . $stmt->error;
}

// Fetch tools generated by users
$query = "
    SELECT 
        user_tools.id AS generation_id, 
        users.username AS user_username, 
        tools.tool_name AS tool_name, 
        tools.tool_cost AS tool_cost, 
        tools.tool_username AS tool_username, 
        tools.tool_password AS tool_password, 
        user_tools.generated_at AS generated_at 
    FROM user_tools 
    JOIN users ON user_tools.user_id = users.id 
    JOIN tools ON user_tools.tool_id = tools.id
";
$stmt = $conn->prepare($query);
$stmt->execute();
$result = $stmt->get_result();

if ($result) {
    $generated_tools = $result->fetch_all(MYSQLI_ASSOC); // Fetch all results as an associative array
} else {
    echo "Error fetching tools: " . $stmt->error;
}

// Function to get the user's country and timezone using IP address
function getUserTimeZoneByIP() {
    $ip = $_SERVER['REMOTE_ADDR'];  // Get the user's IP address
    $access_key = 'YOUR_API_ACCESS_KEY';  // Replace with your IP geolocation API key
    
    // Fetch IP details from the geolocation API
    $url = "http://api.ipstack.com/$ip?access_key=$access_key";
    $response = file_get_contents($url);
    $data = json_decode($response, true);
    
    // Return timezone if available, otherwise default to Asia/Dhaka
    return isset($data['time_zone']['id']) ? $data['time_zone']['id'] : 'Asia/Dhaka';
}

// Get the user's timezone
$user_timezone = getUserTimeZoneByIP();

// Set the timezone for the application
date_default_timezone_set($user_timezone);

// Display the current time in AM/PM format
$current_time = date('Y-m-d h:i:s A');

include 'header.php'; // Admin-side header
?>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h4><i class="fa fa-caret-right fw-r5"></i> View Generated Tools</h4>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="dashboard.php">Dashboard</a></li>
                        <li class="breadcrumb-item active">View Generated Tools</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <?php if (isset($_GET['success']) && $_GET['success'] == '1'): ?>
                <div class="alert alert-success">
                    Tool deleted successfully!
                </div>
            <?php endif; ?>
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">List of Tools Generated by Users</h3>
                    <p>Current Time in Your Region: <span id="live-time"><?php echo $current_time; ?></span></p>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <!-- Form for deleting selected tools -->
                    <form method="post" action="delete_selected_tools.php">
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th><input type="checkbox" id="select-all"> Select All</th>
                                    <th>Users</th>
                                    <th>Tool Name</th>
                                    <th>Tool Username</th>
                                    <th>Tool Password</th>
                                    <th>Date & Time</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($generated_tools as $tool): ?>
                                    <tr>
                                        <td><input type="checkbox" name="tool_ids[]" value="<?php echo $tool['generation_id']; ?>"></td>
                                        <td><?php echo htmlspecialchars($tool['user_username']); ?></td>
                                        <td><?php echo htmlspecialchars($tool['tool_name']); ?></td>
                                        <td><?php echo htmlspecialchars($tool['tool_username']); ?></td>
                                        <td><?php echo htmlspecialchars($tool['tool_password']); ?></td>
                                        <td><?php echo htmlspecialchars(date('Y-m-d h:i:s A', strtotime($tool['generated_at']))); ?></td>
                                        <td>
                                            <a href="delete_generated_tool.php?id=<?php echo $tool['generation_id']; ?>" class="btn btn-sm btn-danger" onclick="return confirm('Are you sure you want to delete this tool?');">Delete</a>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                        <!-- Delete All Button -->
                        <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete the selected tools?');">Delete Selected</button>
                    </form>
                </div>
            </div>
        </div>
    </section>
</div>
<!-- /.content-wrapper -->

<?php include 'footer.php'; // Admin-side footer ?>

<!-- JavaScript to make time live -->
<script>
    // Select All functionality
    document.getElementById('select-all').addEventListener('click', function() {
        const checkboxes = document.querySelectorAll('input[name="tool_ids[]"]');
        checkboxes.forEach(checkbox => {
            checkbox.checked = this.checked;
        });
    });

    function updateTime() {
        // Get current time in user's timezone
        const currentTime = new Date().toLocaleString('en-US', {
            timeZone: '<?php echo $user_timezone; ?>',
            year: 'numeric',
            month: '2-digit',
            day: '2-digit',
            hour: '2-digit',
            minute: '2-digit',
            second: '2-digit',
            hour12: true
        });
        document.getElementById('live-time').innerText = currentTime;
    }
    
    // Update time every second
    setInterval(updateTime, 1000);
</script>
