<?php
session_start();
include '../db.php';
// Set timezone to Asia/Dhaka (Bangladesh Standard Time)
date_default_timezone_set('Asia/Dhaka');

// Ensure only admin can access this page
if ($_SESSION['role'] !== 'admin') {
    header('Location: ../login.php');
    exit;
}

// Retrieve user ID from session
$user_id = $_SESSION['user_id'];

// Get username from the database
$stmt = $conn->prepare("SELECT username FROM users WHERE id = ?");
$stmt->execute([$user_id]);
$user = $stmt->fetch();
$username = $user ? $user['username'] : '';

// Fetch tools generated by users
$stmt = $conn->prepare("
    SELECT 
        user_tools.id AS generation_id, 
        users.username AS user_username, 
        tools.tool_name AS tool_name, 
        tools.tool_cost AS tool_cost, 
        tools.tool_username AS tool_username, 
        tools.tool_password AS tool_password, 
        user_tools.generated_at AS generated_at 
    FROM user_tools 
    JOIN users ON user_tools.user_id = users.id 
    JOIN tools ON user_tools.tool_id = tools.id
");
$stmt->execute();
$generated_tools = $stmt->fetchAll();

include 'header.php'; // Admin-side header
?>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                <h4><i class="fa fa-caret-right fw-r5"></i> View Generated Tools</h4>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="dashboard.php">Dashboard</a></li>
                        <li class="breadcrumb-item active">View Generated Tools</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <?php if (isset($_GET['success']) && $_GET['success'] == '1'): ?>
                <div class="alert alert-success">
                    Tool deleted successfully!
                </div>
            <?php endif; ?>
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">List of Tools Generated by Users</h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Users</th>
                                <th>Tool Name</th>
                                <th>Tool Username</th>
                                <th>Tool Password</th>
                                <th>Date & Time</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($generated_tools as $tool): ?>
                                <tr>
                                    <td><?php echo htmlspecialchars($tool['user_username']); ?></td>
                                    <td><?php echo htmlspecialchars($tool['tool_name']); ?></td>
                                    <td><?php echo htmlspecialchars($tool['tool_username']); ?></td>
                                    <td><?php echo htmlspecialchars($tool['tool_password']); ?></td>
                                    <td><?php echo htmlspecialchars($tool['generated_at']); ?></td>
                                    <td>
                                        <a href="delete_generated_tool.php?id=<?php echo $tool['generation_id']; ?>" class="btn btn-sm btn-danger" onclick="return confirm('Are you sure you want to delete this tool?');">Delete</a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
</div>
<!-- /.content-wrapper -->

<?php include 'footer.php'; // Admin-side footer ?>
