<?php
include '../db.php';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (isset($_POST['category'])) {
        $category = $_POST['category'];

        // Fetch tools that have not been generated by any user
        $stmt = $conn->prepare("
            SELECT id, tool_name 
            FROM tools 
            WHERE category = ? 
              AND id NOT IN (
                SELECT tool_id 
                FROM user_tools
              )
        ");
        $stmt->execute([$category]);
        $tools = $stmt->fetchAll();

        if (empty($tools)) {
            echo '<option value="" disabled>No tools available</option>';
        } else {
            echo '<option value="" disabled selected>Select a tool</option>';
            foreach ($tools as $tool) {
                echo '<option value="' . htmlspecialchars($tool['id']) . '">' . htmlspecialchars($tool['tool_name']) . '</option>';
            }
        }
    } else {
        echo '<option value="" disabled>Invalid category</option>';
    }
}
